name: Frontend Check

on:
  push:
    branches:
      - dev
      - main
      - feature/**

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Project Structure
        run: |
          echo "Mini Shop Monorepo Workflow Running"
          ls
          ls apps